name: Build-Push-Deploy

on:
  push:
    branches:
      - master

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Maven Project
        run: mvn clean package -DskipTests

      - name: Verify Files
        run: |
          pwd
          ls -la
          echo "Checking Dockerfile..."
          test -f Dockerfile && echo "Dockerfile Found" || echo "Dockerfile Missing"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest \
          .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop javaapp || true
            docker rm javaapp || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest

            docker run -d \
              --name javaapp \
              --restart unless-stopped \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/java-docker-app:latest

            docker ps
